# fly.toml app configuration file generated for 23458569chatbot on 2024-03-08T14:20:38+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '23458569chatbot'
primary_region = 'nrt'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  size = 'shared-cpu-1x'
